version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    image: ghcr.io/chilin0525/cloudnative-hw3-frontend-system:0.0.1
    ports:
      - "5173:5173"
    hostname: frontend
    links:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    image: ghcr.io/chilin0525/cloudnative-hw3-backend-system:0.0.1
    ports:
      - "8888:8888"
    hostname: backend
    links:
      - mongodb

  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb.Dockerfile
    image: ghcr.io/chilin0525/cloudnative-hw3-mongodb:0.0.1
    ports:
      - "27017:27017"
    hostname: mongodb