name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      working-directory: backend
      run: npm install

    - name: Run tests and generate coverage
      working-directory: ./backend
      run: npm run test # Ensure this command configures Vitest to output coverage-summary.json in the backend/coverage folder

    - name: Download previous coverage report
      uses: actions/download-artifact@v4
      with:
        # name: coverage-report
        path: ./previous-coverage
      continue-on-error: true # if not exist

    - name: Compare coverage reports
      run: |
        if [ -f "./previous-coverage/coverage-summary.json" ]; then
          current=$(jq '.total.lines.pct' ./backend/coverage/coverage-summary.json)
          previous=$(jq '.total.lines.pct' ./previous-coverage/coverage-summary.json)
          echo "Current Coverage: $current%"
          echo "Previous Coverage: $previous%"
          if [ $(echo "$current < $previous" | bc) -eq 1 ]; then
            echo "Coverage has decreased!"
            exit 1
          fi
        else
          echo "Previous coverage report not found. Assuming first build and passing."
        fi
    
    - name: Store current coverage report as previous for future comparison
      if: success() # only store if the job succeeds
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./backend/coverage/coverage-summary.json

    # - name: Auto Format Code
    #   working-directory: backend
    #   run: npx prettier --write .

    # - name: Commit changes
    #   if: ${{ steps.coverage-check.outputs.coverage < env.PREVIOUS_COVERAGE }}
    #   working-directory: backend
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: Automated code formatting
    #     file_pattern: backend/*

    # - name: Upload Coverage Report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: coverage-report
    #     path: backend/coverage/
